FROM node as builder

COPY package.json package-lock.json /

# Storing node modules on a separate layer will prevent unnecessary npm install at each build
RUN npm config set unsafe-perm true && \
    npm install && \
    mkdir /ng-app && \
    cp -R ./node_modules ./ng-app

WORKDIR /ng-app

COPY . .

# Build Angular app in production mode and store artifacts in dist folder
RUN rm -f ./src/assets/config/settings.env.json

EXPOSE 80

ENTRYPOINT ["npm", "start"]
