/*
Crucible
Copyright 2020 Carnegie Mellon University.
NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
Released under a MIT (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
[DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
Carnegie Mellon(R) and CERT(R) are registered in the U.S. Patent and Trademark Office by Carnegie Mellon University.
DM20-0181
*/

/**
 * Steamfitter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DispatchTaskResult {
    id?: string;
    dispatchTaskId?: string;
    vmId?: string;
    vmName?: string;
    apiUrl?: string;
    inputString?: string;
    expirationSeconds?: number;
    iterations?: number;
    intervalSeconds?: number;
    status?: DispatchTaskResult.StatusEnum;
    expectedOutput?: string;
    actualOutput?: string;
    sentDate?: Date;
    statusDate?: Date;
    dateCreated?: Date;
    dateModified?: Date;
    createdBy?: string;
    modifiedBy?: string;
}
export namespace DispatchTaskResult {
    export type StatusEnum = 'pending' | 'queued' | 'sent' | 'cancelled' | 'expired' | 'failed' | 'succeeded' | 'error';
    export const StatusEnum = {
        Pending: 'pending' as StatusEnum,
        Queued: 'queued' as StatusEnum,
        Sent: 'sent' as StatusEnum,
        Cancelled: 'cancelled' as StatusEnum,
        Expired: 'expired' as StatusEnum,
        Failed: 'failed' as StatusEnum,
        Succeeded: 'succeeded' as StatusEnum,
        Error: 'error' as StatusEnum
    };
}



