# need to build with this command: dotnet publish -c Release -o bin/publish

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine

COPY bin/publish/. /app/

WORKDIR /app

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000

CMD ["dotnet", "Steamfitter.Api.dll"]

# docker run —-network steamfitter-network -p 127.0.0.1:4400:5000 --name steamfitter-api -d steamfitter/api
