# Description: Headings should not end with punctuation.
# Headings that are questions are ok, so ? is omitted
extends: existence
message: "Don't end a heading with punctuation."
nonword: true
level: error
scope: heading
action:
  name: edit
  params:
    - trim_right
    - ".,!?;:"
tokens:
  - '[.!,;:]\s*$'
