#
# Enforces the use of Oxford Commas
# From the Microsoft Style Guide: https://github.com/errata-ai/Microsoft
#
extends: existence
message: "Use the Oxford comma in '%s'."
link: https://docs.microsoft.com/en-us/style-guide/punctuation/commas
scope: sentence
level: error
nonword: true
tokens:
  - '(?:[^\s,]+,){1,} \w+ (?:and|or) \w+[.?!]'
