---
# Source: Google (https://github.com/errata-ai/Google)
# Description: Checks for double spacing and prompts to remove if found.
extends: existence
message: "'%s' should have one space."
link: "https://developers.google.com/style/sentence-spacing"
level: error
nonword: true
action:
  name: remove
tokens:
  - "[a-z][.?!] {2,}[A-Z]"
  - "[a-z][.?!][A-Z]"
exceptions:
  - t.C # Exception put in place for Rocket.Chat
# Portions of this page are reproduced from work created and [shared by Google](https://developers.google.com/readme/policies)
# and used according to terms described in the [Creative Commons 4.0 Attribution License](https://creativecommons.org/licenses/by/4.0/).
