# Description: Checks for double spacing and prompts to remove if found.
extends: existence
message: "'%s' should have one space."
level: error
nonword: true
action:
  name: remove
tokens:
  - "[a-z][.?!] {2,}[A-Z]"
  - "[a-z][.?!][A-Z]"
exceptions:
  - t.C # Exception put in place for Rocket.Chat
