# Description: Converts smart quotes to straight quotes
extends: substitution
message: Do not use smart quotation marks. Use %s rather than %s.
level: error
nonword: true
scope: raw
action:
  name: replace
swap:
  ‘|’: "'"
  ‟|″|‶|"|": '"'
