name: Auto-label Documentation Update Issues

on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/1-documentation-update.yml

      - name: Set labels based on application field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: application
          block-list: |
            None
            General Docs Update - Not Application Specific
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set labels based on update_type field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: update_type
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}
