name: Auto-label Documentation Update Issues

on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract issue body
        id: extract_body
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            return issueBody;

      - name: Determine labels
        id: determine_labels
        run: |
          LABELS=""

          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Alloy"; then
            LABELS="$LABELS Alloy"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Blueprint"; then
            LABELS="$LABELS Blueprint"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Caster"; then
            LABELS="$LABELS Caster"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] CITE"; then
            LABELS="$LABELS CITE"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Gallery"; then
            LABELS="$LABELS Gallery"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Gameboard"; then
            LABELS="$LABELS Gameboard"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Player"; then
            LABELS="$LABELS Player"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Steamfitter"; then
            LABELS="$LABELS Steamfitter"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] TopoMojo"; then
            LABELS="$LABELS TopoMojo"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] General"; then
            LABELS="$LABELS General"
          fi



          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] New feature"; then
            LABELS="$LABELS New feature"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Correction"; then
            LABELS="$LABELS Correction"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Enhancement"; then
            LABELS="$LABELS Enhancement"
          fi
          if echo "${{ steps.extract_body.outputs.result }}" | grep -q "- \[x\] Other"; then
            LABELS="$LABELS Other"
          fi

          echo "LABELS=$(echo $LABELS | xargs)" >> $GITHUB_ENV

      - name: Add labels to issue
        uses: actions/github-script@v7
        with:
          script: |
            const labels = process.env.LABELS.split(' ');
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
